In [1]:
import numpy as np

# Search

In [2]:
#Liner_Search
def linear_search(a, x): 
    for k in range(0,len(a)): 
        if a[k] == x: 
            return k
    return -1


unsorted=np.array([12,423,9,14,100,65,34,90])
sort_arr=np.array([1,10,12,23,45,74,1002])
print("Unsorted array:")
print(linear_search(unsorted,12))
print(linear_search(unsorted,34))
print(linear_search(unsorted,81))
print("Sorted array:")
print(linear_search(sort_arr,10))
print(linear_search(sort_arr,12))
print(linear_search(sort_arr,74))

Unsorted array:
0
6
-1
Sorted array:
1
2
5


In [3]:
#Binary_search

def binary_search(a,x):
    st = 0
    ed = len(a)-1
    while( st<=ed ):
        mid = (st+ed)//2
        if a[mid] == x :
            return mid
        else:
            if x < a[mid]:
                ed = mid - 1
            else:
                st = mid + 1
    return "Not found"

sort_arr=np.array([1,10,12,23,45,74,1002])
print("Sorted array:")
print(binary_search(sort_arr,10))
print(binary_search(sort_arr,12))
print(binary_search(sort_arr,74))

Sorted array:
1
2
5


# Sorting

In [10]:
#insertion sort

def insertion_sort(A,n):
    for i in range(1,n):
        key=A[i]
        j=i-1
        while j>=0 and A[j]>key:
            A[j+1]=A[j]
            j-=1
        A[j+1]=key
        
        
arr=np.array([12,23,1,1002,45,74,10])
insertion_sort(arr,len(arr))
print(arr)

[   1   10   12   23   45   74 1002]


In [14]:
#selection sort
def selection_sort(A,n):
    for i in range(n-1):
        m=0
        for j in range(1,n-i):
            if A[j]>A[m]:
                m=j
        A[n-i-1],A[m]=A[m],A[n-i-1]
    

arr=np.array([12,423,9,14,100,65,34,90])
selection_sort(arr,len(arr))
print(arr)

[  9  12  14  34  65  90 100 423]


In [15]:
#bubble sort
def bubble_sort(A,n):
    for i in range(0,n-1):
        swapping=False
        for j in range(n-i-1):
            if A[j]>A[j+1]:
                A[j+1],A[j]=A[j],A[j+1]
                swapping=True
        if not swapping:
                return

arr=np.array([73,12,23,9,14,1002,6,34,90])
bubble_sort(arr,len(arr))
print(arr)

[   6    9   12   14   23   34   73   90 1002]


In [16]:
#merge sort
def merge_sort(A,l,r):
    if l<r:
        mid=(l+r)//2
        merge_sort(A,l,mid)
        merge_sort(A,mid+1,r)
        merge(A,l,mid,r)

def merge(A,l,m,r):
    i=l
    j=m+1
    B=np.array([])
    while i<=m and j<=r:
        if A[j]<A[i]:
            B=np.append(B,A[j])
            j+=1
        else:
            B=np.append(B,A[i])
            i+=1
    if i>m:
        i=j
        m=r
    while i<=m:
        B=np.append(B,A[i])
        i+=1
    for k in range(l,r+1):
        A[k]=B[k-l]


arr=np.array([73,12,23,9,14,1002,6,34,90])
merge_sort(arr,0,len(arr)-1)
print(arr)

[   6    9   12   14   23   34   73   90 1002]


In [17]:
#quick sort

def quick_sort(A,l,r):
    if l<r:
        q=partition(A,l,r)
        quick_sort(A,l,q-1)
        quick_sort(A,q+1,r)

def partition(A,l,r):
    pivot=A[l]
    j=l+1
    i=l
    while j<=r:
        if A[j]<pivot:
            A[i+1],A[j]=A[j],A[i+1]
            i=i+1
        j+=1
    A[l],A[i]=A[i],A[l]
    return i
    
a=np.array([73,12,23,9,14,1002,6,34,90])
quick_sort(a,0,len(a)-1)
print(a)      

[   6    9   12   14   23   34   73   90 1002]


In [18]:
#Heap sort
def Maxheapify(A,i,n):
    l=2*i+1
    r=2*i+2
    if l>n:
        return
    if r>n:
        largest=l
    else:
        if A[l]>A[r]:
            largest=l
        else:
            largest=r
    if A[largest]>A[i]:
        A[i],A[largest]=A[largest],A[i]
        Maxheapify(A,largest,n)
        
        
def build_heap(A):
    n=len(A)-1
    k=int((n-1)//2)
    for i in range(k+1,-1,-1):
        Maxheapify(A,i,n)
        #print(A)
    
def heapSort(A):
    build_heap(A)
    n=len(A)-1
    heapsize=n
    for i in range(n,0,-1):
        heapsize-=1
        A[0],A[i]=A[i],A[0]
        Maxheapify(A,0,heapsize)
    

In [19]:
arr=[2,3,45,6,7,8,90,22]
heapSort(arr)
print(arr)

[2, 3, 6, 7, 8, 22, 45, 90]


In [20]:
#counting sort
def counting_sort(A):
    B=[0]*10
    for i in A:
        B[i]+=1
    for k in range(1,10):
        B[k]+=B[k-1]
    C=[0]*len(A)
    for k in A[-1::-1]:
        if B[k]>0:
            C[B[k]-1]=k
            B[k]-=1
    return C
A=[4,8,4,8,5,4,8,3,5,2,3,4,5,4]
print(counting_sort(A))


[2, 3, 3, 4, 4, 4, 4, 4, 5, 5, 5, 8, 8, 8]
